name: CI/CD Deployment

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the Docker image locally on the runner
      - name: Build Docker image
        run: docker build -t myapp:latest .

      # Save the Docker image to a tar file
      - name: Save Docker image to tarball
        run: |
          docker save -o myapp.tar myapp:latest
          ls -la myapp.tar  # Verify file exists and check size
          chmod 644 myapp.tar  # Ensure file has proper permissions

      # Transfer the tarball to your Linux server
      - name: Copy image tarball to server
        uses: appleboy/scp-action@v0.1.4  # Use specific version instead of master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "myapp.tar"
          target: "~/"
          debug: true  # Enable debug mode to get more information

      # Deploy on the Linux server: load the image and run the container
      - name: Deploy on Linux server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            ls -la ~/myapp.tar  # Verify file exists on server
            docker load -i ~/myapp.tar
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --name myapp -p 3000:3000 myapp:latest
